Repository paulohgs/Lazyless, pull requests merged in 2022-10, with the labels that each got.

#64 Adicionando Launch
  Lazyless/Base.lproj/LaunchScreen.storyboard
Labels: enhancement

#66 delete activities
  Lazyless/View/CardActivityView.swift
  Lazyless/ViewController/CustomTableViewController.swift
Labels: enhancement, hacktoberfest-accepted

#67 correção no nome do app e adicionada seção de contribuição
  README.md
Labels: enhancement, hacktoberfest-accepted

#68 mudando o json
  Lazyless/database.json
Labels: bug, hacktoberfest-accepted

#73 Yago on lazyless
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/View/CircularProgressView.swift
  Lazyless/ViewController/ActivityViewController.swift
  Lazyless/ViewController/CustomTableViewController.swift
  Lazyless/ViewController/MainController.swift
Labels: enhancement, hacktoberfest-accepted
