Repository paulohgs/Lazyless, pull requests merged in 2022-09, with the labels that each got.

#14 Dev
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Model/ActivityModel.swift
  Lazyless/Model/PersonaModel.swift
  Lazyless/Protocols/ViewCoding.swift
  Lazyless/ViewController/HomeViewController.swift
  Lazyless/ViewController/MainController.swift
  Lazyless/database.json
Labels: documentation

#16 coracao ajeitado
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Assets.xcassets/h.imageset/h.svg
  Lazyless/Assets.xcassets/heart.imageset/Contents.json
  Lazyless/Assets.xcassets/heart.imageset/heart.svg
  Lazyless/Model/PersonaModel.swift
  Lazyless/View/HeartView.swift
  Lazyless/ViewController/MainController.swift
Labels: enhancement

#18 9 criar view do balao de falas
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Assets.xcassets/darkGrey.colorset/Contents.json
  Lazyless/Model/SpeakModel.swift
  Lazyless/View/SpeakView.swift
  Lazyless/ViewController/MainController.swift
  Lazyless/ViewModel/SpeakViewModel.swift
Labels: enhancement

#22 20 criar testes para os models
  Lazyless.xcodeproj/project.pbxproj
  Lazyless.xcodeproj/xcshareddata/xcschemes/Lazyless.xcscheme
  Lazyless/Model/ActivityModel.swift
  Lazyless/Model/PersonaModel.swift
  Lazyless/Model/SpeakModel.swift
  Lazyless/ViewModel/SpeakViewModel.swift
  LazylessTests/Models/SpeakModelTests.swift
Labels: documentation

#32 30 create branch test
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Model/ActivityModel.swift
  Lazyless/Protocols/ViewCoding.swift
  Lazyless/View/SliderView.swift
  Lazyless/ViewController/ActivityViewController.swift
  Lazyless/ViewController/MainController.swift
  Lazyless/database.json
Labels: enhancement

#41 Adicionado fluxo final do usuário de adicionar o card e atualizar tab…
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Cell/CustomTableViewCell.swift
  Lazyless/Protocols/ActivityToTableViewDelegate.swift
  Lazyless/Protocols/ActivityViewDelegate.swift
  Lazyless/View/CardActivityView.swift
  Lazyless/View/SliderView.swift
  Lazyless/ViewController/ActivityViewController.swift
  Lazyless/ViewController/CustomTableViewController.swift
  Lazyless/ViewController/MainController.swift
Labels: bug

#47 empty state da tableView
  Lazyless/ViewController/ActivityViewController.swift
  Lazyless/ViewController/CustomTableViewController.swift
Labels: enhancement

#48 Criação do delegate do cardActivity para MainController
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Cell/CustomTableViewCell.swift
  Lazyless/Model/PersonaModel.swift
  Lazyless/Protocols/AffinityDelegate.swift
  Lazyless/View/CardActivityView.swift
  Lazyless/View/CircularProgressView.swift
  Lazyless/View/HeartView.swift
  Lazyless/ViewController/CustomTableViewController.swift
  Lazyless/ViewController/MainController.swift
Labels: enhancement

#52 levelUp workings
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Model/PersonaModel.swift
  Lazyless/Protocols/NextLevelDelegate.swift
  Lazyless/View/CircularProgressView.swift
  Lazyless/View/HeartView.swift
  Lazyless/View/SpeakView.swift
  Lazyless/ViewController/MainController.swift
Labels: bug

#61 Criação do fluxo de falas de forma dinamica
  Lazyless/Model/SpeakModel.swift
  Lazyless/Services/ReadJson.swift
  Lazyless/View/SpeakView.swift
  Lazyless/ViewController/MainController.swift
  Lazyless/database.json
Labels: enhancement

#62 Release 2.0: Fixing SpeakModel, SpeakView and adding question mark animation on character
  Lazyless.xcodeproj/project.pbxproj
  Lazyless/Model/SpeakModel.swift
  Lazyless/Services/ReadJson.swift
  Lazyless/View/SpeakView.swift
  Lazyless/ViewController/CustomTableViewController.swift
  Lazyless/ViewController/MainController.swift
  Lazyless/database.json
  Lazyless/questionMark.json
Labels: bug, enhancement
